export const TOGGLE_LOGIN_DIALOG = 'TOGGLE_LOGIN_DIALOG';
export const TOGGLE_SIDEDRAWER = 'TOGGLE_SIDEDRAWER';
export const TOGGLE_NEW_PURCHASE_DIALOG = 'TOGGLE_NEW_PURCHASE_DIALOG';
export const TOGGLE_AUTH_LOADING = 'TOGGLE_AUTH_LOADING';
export const ERROR_LOGIN = 'ERROR_LOGIN';
export const CLEAR_LOGIN_ERROR = 'CLEAR_LOGIN_ERROR';

export const LOGIN_SUCCESS = 'LOGGIN_SUCCESS';
export const LOGIN_START = 'LOGGIN_START';
