export const TOGGLE_LOGIN_DIALOG = 'TOGGLE_LOGIN_DIALOG';
export const TOGGLE_SIDEDRAWER = 'TOGGLE_SIDEDRAWER';
export const TOGGLE_NEW_PURCHASE_DIALOG = 'TOGGLE_NEW_PURCHASE_DIALOG';
export const TOGGLE_AUTH_LOADING = 'TOGGLE_AUTH_LOADING';
export const ERROR_LOGIN = 'ERROR_LOGIN';
export const CLEAR_LOGIN_ERROR = 'CLEAR_LOGIN_ERROR';
export const TOGGLE_AUTH_STATE = 'TOGGLE_AUTH_STATE';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_START = 'LOGIN_START';
export const LOGOUT_START = 'LOGOUT_START';
export const LOGOUT_USER = 'LOGOUT_USER';

export const CHECK_STORAGE_TOKEN = 'CHECK_STORAGE_TOKEN';
export const START_TOKEN_TIMEOUT = 'START_TOKEN_TIMEOUT';
